### ISSUE TITLE
Error In SINDyLib when Running for loop for Double Pendulum

### ISSUE THREAD

**Issue by kevinegan31** [dynamicslab/SINDy-PI#2]
Hello,

I am currently trying to run the downloadable code for the Double Pendulum. I downloaded and am running the file and get the error 

```
Index in position 2 exceeds array bounds (must not exceed 1).

Error in SINDyLib (line 53)
Data(:,Index)=dX(:,2).^2;

Error in DoublePendulum_Main (line 125)
    [SINDy_Data,SINDy_Struct]=SINDyLib(Data,dData(:,iter),iter,u,Highest_Poly_Order,Highest_Trig_Order,Highest_U_Order,Highest_dPoly_Order);
```

Which I am finding difficult to work around since the data provided seems to have more than 1 column. Please let me know if there is a simple fix for this issue.

Thanks

**Comment by KKahirman** [comment]
Hi,

Thanks for finding this bug! I somehow uploaded a wrong function file and that's why it is not working, the problem is fixed after I uploaded the function file, please download the updated file and have a try.

Thanks!
